# Generated by Django 4.1.11 on 2023-09-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChildrenLR',
            new_name='Children_law',
        ),
        migrations.RenameModel(
            old_name='CommonsLR',
            new_name='Commons_law',
        ),
        migrations.RenameModel(
            old_name='MensLR',
            new_name='Mens_law',
        ),
        migrations.RenameModel(
            old_name='TransgenderLR',
            new_name='Transgender_law',
        ),
        migrations.RenameModel(
            old_name='WomenLR',
            new_name='Women_law',
        ),
    ]
