# Generated by Django 4.1.11 on 2023-09-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_alter_commons_law_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commons_law',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='laws/'),
        ),
    ]
